### ISSUE TITLE
윈도우 호환성

### ISSUE THREAD

**Issue by whoo24** [outsideris/node.js-programming#1]
윈도우에서 6장 Simple-Web 따라하고 있습니다.
노드를 기본 설치하고, 환경 변수 등록된 상태에서 다음을 수행했습니다.

node> npm install express -g
node> express simpleweb
node> cd simpleweb
node\simpleweb> npm install
node\simpleweb> node app.js

로컬에 접속하면 다음 에러가 납니다.
500 Error: Cannot find module './lib/jade'

소스코드 다운로드해서 실행해도 마찬가지구요
- application-name@0.0.1 C:\www\chapter-06\simpleweb
  - express@2.5.8
    - connect@1.8.6
      - formidable@1.0.9
    - mime@1.2.4
    - mkdirp@0.3.0
    - qs@0.4.2
  - jade@0.21.0
    - commander@0.5.2
    - mkdirp@0.3.0

npm list는  위와 같고요.
os는 윈7 64비트, node는 v0.6.13 입니다.

**Comment by outsideris** [comment]
테스트를 해보았는데 npm v1.1.9 윈도우버전에서 버그가 있는것 같습니다.
예제도 대부분 윈도우에서 테스트하긴 했는데 그때는 npm v1.1.9가 아니었어서요..
일단 node 0.6.12에 포함된 npm 1.1.4를 설치하니까 이상없이 동작하고 있습니다.

1.1.9를 쓸 때는 이상하게 node_moduels/jade/lib 안에 jade.js라는 파일이 생기지 않아서
발생한 오류입니다. 좀더 테스트해보아야겠지만 npm 윈도우용의 오류로 보입니다.
좀더 테스트해보고 npm쪽에 버그리포팅해야겠네요.

**Comment by outsideris** [comment]
집에서 다시 테스트해보려고 했더니 오늘 jade@0.22.0이 나왔습니다.
jade와 npm 1.1.9와의 충돌이 있었나보네요
npm 1.1.9에서도 jade@0.22.0은 제대로 설치되는 것을 확인했습니다.
