### ISSUE TITLE
8장 방 만들기 할 때 500 에러

### ISSUE THREAD

**Issue by whoo24** [outsideris/node.js-programming#2]
8장 simple chat 을 따라하고 있는데 방제를 입력 후 방 만들기를 누르면 500 Error: failed to locate view "makeRoom" 에러가 납니다.

app.js 의

> res.render('makeRoom', {

을

> res.render('makeroom', {

으로 바꾸거나

view/makeroom.jade 를 view/makeRoom.jade 로 이름을 바꿔야 할 것 같습니다.

**Comment by outsideris** [comment]
최근에 오류수정하면서 ( https://github.com/outsideris/node.js-programming/commit/def74ccde33315f19cd90a6083000cfecf775c3e ) 테스트해보았던 부분인데 집에가면 다시 확인해봐야겠네요.
테스트하신 환경은 아래 이슈올리실때 적으신 환경과 동일하신가요?

**Comment by whoo24** [comment]
OS는 버추얼박스에 리눅스민트 12버전이고 나머지 소프트웨어는 동일합니다.
Node 0.6.13 입니다.

**Comment by outsideris** [comment]
https://github.com/outsideris/node.js-programming/commit/188dd9de4adc7a9ee371ea692230b62d0912eaf5 
에서 수정하였습니다.
