### ISSUE TITLE
채팅 예제가 최신 node.js  버전과 호환이 안됩니다.

### ISSUE THREAD

**Issue by SeraClinic** [outsideris/node.js-programming#3]
안녕하세요,

집필하신 책 보면서 node.js 연습중인데요, 채팅 예제가 제대로 작동을 안하는 듯 하네요.

최신 node.js  버전과 호환이 안되는거 같은데 체크 부탁드립니다^^

좋은 책 열심히 보고 있습니다!!

**Comment by outsideris** [comment]
정확히 어떤 예제가 안되는지 말씀해 주시면 감사하겠습니다.
노드쪽이 좀 빠르게 변해서 노드버전 문제일수도 있고 모듈버전 문제일수도 있거든요.

**Comment by SeraClinic** [comment]
아 죄송합니다 어떤부분인지 말씀안드렸네요^^;

챕터8  채팅 예제 입니다 웹서버에 올리고 실행하면 오류가 나거든요.. 지금밖이라서 정확히 오류 내용을 말씀 못드리겠네요;

익스프레스 3.0 으로 업데이트 되면서 생기는 문제로 보였습니다 io 소캣 실행할때 http 객체 넘겨주는부분이 문제였거든요

답변 주셔서 감사합니다~!

2012년 9월 16 일요일에 Outsidernotifications@github.com님이 작성:

**Comment by outsideris** [comment]
아~ 일단 짬이날때 확인해 보겠습니다.
리포팅 주셔서 감사합니다. ㅠㅠ

모듈에 관련해서는 호환성 문제때문에 `package.json`에 버전을 명시해놓았을 건데 확인해봐야겠네요. 익스프레스 3.0에서는 API자체가 많이 바뀌었기 때문에 3.0으로 돌리면 오류가 생길여지는 많이 있을 것입니다. 

github에 올린 소스에는 버전을 명시해놨는데 직접 소스타이핑해서 3.0으로 돌리신건가요? 아님 다른 문제로 익스프레스 3.0이 적용된건가요?

아직 소스는 못돌려봤지만 말씀하신 사항으로 추측했을 때 다음문제로 보입니다.
기존에는 express로 생성한 코드가 HttpServer인스턴스였는데 3.0부터는 달라졌습니다.
Socket.IO에 전달해야 하는 객체는 HttpServer인스턴스여야 하는데 타입이 달라서 발생하는 문제이기 때문에 Socket.iO를 express 3.0에서 사요하시려면 직접 서버를 생성행성해서 전달해야 합니다.

```
var app = express()
  , http = require('http')
  , server = http.createServer(app)
  , io = require('socket.io').listen(server);
```

위처럼 직접 서버객체를 생성해서 전달해야 합니다. 자세한 내용은 [익스프레스 마이그레이션 가이드](https://github.com/visionmedia/express/wiki/Migrating-from-2.x-to-3.x)에 잘 나와있습니다.

이번 익스프레스처럼 버전이 올라가서 버전이 달라진 경우는 어떻게 적용해야할지는 좀 고민입니다.
여기의 소스를 고치면 또 이전버전의 모듈과 사용하는 사람들이 오류가 날꺼라서요.
특정예제뿐 아니라 전체적인 변경이 이뤄져야 하기도 하고요.

**Comment by outsideris** [comment]
0.8용 브랜치를 따로 만들었습니다 이슈는 이제 닫네요
