### ISSUE TITLE
아래와 같은 오류가 예제마다 계속 일어납니다 ㅠㅜ 해결해주세요

### ISSUE THREAD

**Issue by Sim-jaeil** [outsideris/node.js-programming#4]
![ ](https://f.cloud.github.com/assets/3378203/96492/8f175922-66b6-11e2-81bc-c58e8e62f216.png)

**Comment by outsideris** [comment]
해당 문제는 express가 3.x로 올라가면서 사용방식이 달라졌기에 발생한 문제입니다.
그래서 package.json에 버전명시가 되어 있는데 명시적으로 최신 버전을 사용하신듯 합니다
자세한 내용은 [express 마이그레이션가이드](https://github.com/visionmedia/express/wiki/Migrating-from-2.x-to-3.x)를 참고하시면 되고 위의 올려주신 문제는 app.js를 다음과 같이 수정해 주시면 됩니다.

```
-var app = module.exports = express.createServer();
+var app = module.exports = express();

...

-app.listen(3000);
-console.log("Express server listening on port %d in %s mode", app.address().port, app.settings.env);
+var server = app.listen(3000);
+console.log("Express server listening on port %d", server.address().port);
```

(앞에 -가 붙은 줄은 기존의 소스중 제거한 부분이고 +가 있는 라인은 새로 추가한 부분입니다.)

버전 호환성 문제를 겪는 분들이 좀 있는것 같아서 최선 노드 버전과 모듈호환성에 맞춰서 소스를 전체적으로 업데이트해서 제공해 드리는 것을 고민하고 있습니다.

**Comment by Sim-jaeil** [comment]
![image](https://f.cloud.github.com/assets/3378203/102181/e2321ec6-6913-11e2-8742-44228344f820.png)

**Comment by Sim-jaeil** [comment]
설명대로 바꾸어보아도 위와 같은 오류가 나옵니다.

**Comment by outsideris** [comment]
express 3.0.6으로 설치하신게 아니신가요?
npm ls 하셔서 설치된 npm 모듈 리스트를 알려주세요. 앞에 설정에서는 express 3.0.6으로 설치된 걸로 보였는데 오류가 그렇게 나오면 express 2.5.x 버전이 설치되어 있으신것 같은데요요

**Comment by Sim-jaeil** [comment]
이렇게 보내드리면 되나요?? 펌웨어 프로그램만 하다가 조금 생소하네요 ^^;

![image](https://f.cloud.github.com/assets/3378203/105267/1adb76b4-69a5-11e2-90d1-377e2069defe.png)

근데 프로젝트마다 다르네요 모든 NPM모듈을 글로벌로 설치해버려야 하나요??
프로젝트마다  npm install express 라고 해서 설치했는데 이런 결과가 나오네요??

![image](https://f.cloud.github.com/assets/3378203/105344/37fc20aa-69a9-11e2-8419-7779e31e99c5.png)

그래서 몽고 디비에는 3.0.6이 깔려있는듯 하여, 소스코드를 바꾸고 실행해 보았습니다.

![image](https://f.cloud.github.com/assets/3378203/105355/dc774c40-69a9-11e2-9ef0-12f7acf41496.png)

**Comment by outsideris** [comment]
처음에 주신 내용과 지금 중간에 주신 내용이 틀린데요.
예제 소스 프로젝트에는 package.json내에 의존성이 표시되어 있습니다. 그래서 그냥 설치하시면(로컬로 설치하셔야 합니다. 글로벌은 CLI 용도입니다.) 2.5.11이 설치되어야 정상적입니다. 3.0.6으로 설치된 곳은 뭔가 다른식으로 설치하신게 아닌가 싶네요.
2.5.x와 3.0.x의 차이는 앞에서 말씀드렸고요 마지막에 주신 스크린샷에서 나온 오류는 mongoDB에 접속할 수 없어서 나온 오류입니다. 몽고DB가 localhost:27017로 접속가능한 상태인지 확인해 주세요.
