### ISSUE TITLE
socket.io 1.x 버전에서는 채팅예제가 동작하지 않습니다.

### ISSUE THREAD

**Issue by parduck** [outsideris/node.js-programming#6]
rooms.js 내의 
io.configure 관련 내역이 동작해야 합니다.

**Comment by outsideris** [comment]
1.0에서 API가 많이 달라져서 그렇습니다. 전체 예제의 코드를 최신 버전으로 업데이트하는 걸 고려해 봐야하는데 일단 말씀하신 채팅 예제만 업데이트했습니다.

Node.js v4.3, express 4.x, socket.io 1.4.5에서 테스트를 했습니다. 
https://github.com/outsideris/node.js-programming/tree/node-4.x
